- hosts: build-windows-slaves
  
  roles:
    - { role: ds-builder }
    - { role: exe-signer, cert_path: certs/asc.pfx }
    - { role: exe-signer, cert_path: certs/nct.pfx }
    - { role: aws-cli }
    - { role: github-user }
    - { role: aws-cli, user_profile_path: "C:\\Msys" }
    - { role: github-user, user_profile_path: "C:\\Msys" }
    - { role: vs-license }
