---
- name: Install requred packages
  apt: 
    name: "{{ qt_build_sourcecode_packages }}"
  become: yes

- name: download qt source
  get_url:
    url: "{{ qt_src_url }}"
    dest: "./{{ qt_src_arch }}"

# - name: create dir for qt source
#   file:
#     path: "{{ qt_src_dest }}"
#     state: "absent"
#   become: yes

# - name: unarchive qt source
#   unarchive:
#     src: "./{{ qt_src_arch }}"
#     dest: "{{ qt_src_dest }}"
#     remote_src: yes

- name: unarchive qt source
  shell: tar -xf ./{{ qt_src_arch }}
  args:
    creates: "{{ qt_src_dest }}"

- name: configure qt source
  shell: "./configure {{ qt_conf_opt }}"
  args:
    chdir: "{{ qt_src_dest }}"
    creates: "{{ qt_src_dest }}/Makefile"

- name: make qt
  make:
    params:
        MAKEFLAGS: "-e -j 4"
    chdir: "{{ qt_src_dest }}"

- name: install qt
  make:
    chdir: "{{ qt_src_dest }}"
    target: install
  become: yes

- name: Copy icu libs
  shell: cp -a /usr/lib/x86_64-linux-gnu/libicu*.so* {{ qt_install_path }}/lib
  become: yes

- name: create qtchooser config directory
  file:
    path: "{{ qtchooser_conf_path | dirname }}"
    state: "directory"
  become: yes

- name: copy qtchooser config
  template:
    src: "qtchooser/qt.conf.jn2"
    dest: "{{ qtchooser_conf_path }}"
  become: yes
