---
program_files: "{{ program_files_64 }}"

msys2_path: C:\msys64

chocolatey_packages:
  -
    name: 7zip
  -
    name: awscli
  -
    name: git
  -
    name: innosetup
    version: "5.6.1"
  -
    name: jdk8
  -
    name: jre8
  -
    name: jq
  -
    name: msys2
    params: "/InstallDir:{{ msys2_path }} /NoPath"
    version: "20210105.0.0"
  -
    name: nasm
  -
    name: nodejs
    version: "10.17.0"
  -
    name: pstools
  -
    name: python2
  -
    name: strawberryperl
  -
    name: tortoisesvn

packages:
  -
    name: Visual Studio Community 2015
    url: https://download.microsoft.com/download/e/4/c/e4c393a9-8fff-441b-ad3a-3f4040317a1f/vs_community.exe
    product_id: '{79b486b9-c5f0-4096-a00c-8351f59587c2}'
    arguments: '{{ vs_args }}'
    path: "{{ download_path }}\\vs.exe"
  -
    name: Windows 10 SDK
    url: http://download.microsoft.com/download/C/D/8/CD8533F8-5324-4D30-824C-B834C5AD51F9/standalonesdk/sdksetup.exe
    product_id: '{5eb6fbea-73ee-4a8e-9042-110704768d7f}'
    arguments: '{{ w10sdk_args }}'
    path: "{{ download_path }}\\w10sdk.exe"
  -
    name: QT 5.9
    url: https://download.qt.io/official_releases/qt/5.9/5.9.8/qt-opensource-windows-x86-5.9.8.exe
    creates_path: "{{ qt_path }}"
    arguments: '{{ qt_args }}'
    path: "{{ download_path }}\\qt.exe"
  -
    name: QT 5.6
    url: http://download.qt.io/new_archive/qt/5.6/5.6.3/qt-opensource-windows-x86-msvc2015_64-5.6.3.exe
    creates_path: "{{ qt56_path }}"
    arguments: '{{ qt56_args }}'
    path: "{{ download_path }}\\qt56.exe"

msys2_packages:
  - { name: m4,   binary: m4.exe }
  - { name: make, binary: make.exe }

exec_path:
  - '{{ qt_path }}\5.9.8\msvc2015_64\bin'
  - '{{ msys2_path }}\usr\bin'
  - '%SystemDrive%\Windows\ServiceProfiles\LocalService\AppData\Roaming\npm'
  - '{{ program_files_32 }}\Microsoft Visual Studio 14.0\VC\bin'
  - '{{ program_files_32 }}\Windows Kits\10\bin\x64'
  - '{{ program_files_64 }}\NASM'
