---
- name: Wait for Jenkins to start up before proceeding
  uri:
    url: "http://localhost:{{ jenkins_http_port }}/cli/"
    method: GET
    return_content: "yes"
    timeout: 5
    body_format: raw
    follow_redirects: "no"
    status_code: 200,403
  register: result
  until: (result.status == 403 or result.status == 200) and (result.content.find("Please wait while") == -1)
  retries: 5
  delay: 60
  changed_when: false
  check_mode: false

- name: Execute setup script
  jenkins_script:
    script: "{{ lookup('template', 'setup.groovy.jn2')}}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: "http://localhost:{{ jenkins_http_port }}/"
