---
- name: Add repos apt keys
  apt_key:
    keyserver: "{{ item.keyserver }}"
    id: "{{ item.keyid }}"
  when:
    - item.keyserver is defined
    - item.keyid is defined
  with_items: "{{ repositories }}"
  become: yes

- name: Add required repos
  apt_repository:
    repo: "{{ item.repo }}"
    codename: "{{ item.codename | default(omit) }}"
    filename: "{{ item.name | default(omit) }}"
  with_items: "{{ repositories }}"
  become: yes

- name: Install required packages
  apt: 
    name: "{{ packages }}"
    state: latest
    force: yes
  become: yes

- block:
  - name: Config git user.name
    git_config:
      name: user.name
      scope: global
      value: "{{ git_user_name }}"

  - name: Config git user.email
    git_config:
      name: user.email
      scope: global
      value: "{{ git_user_email }}"
  become: yes
  become_user: "{{ ssh_user }}"

- block:
  - name: Create ssh data directory
    file:
      path: "{{ ssh_data_path }}"
      state: directory
      mode: "0700"

  - name: Disable ssh host ip checking
    blockinfile:
      path: "{{ ssh_config_file }}"
      create: yes
      mode: "0600"
      marker_begin: "CHECK HOST IP BEGIN"
      marker_end: "CHECK HOST IP END"
      block: |
        CheckHostIP=no

  - name: Configure github private key
    blockinfile:
      path: "{{ ssh_config_file }}"
      create: yes
      mode: "0600"
      marker_begin: "GITHUB BEGIN"
      marker_end: "GITHUB END"
      block: |
        Host github.com
          IdentityFile {{ ssh_priv_key_file }}

  - name: Create ssh private keys directory
    file:
      path: "{{ ssh_priv_key_file | dirname }}"
      state: "directory"

  - name: Copy github private key
    copy: 
      src: "{{ ssh_priv_key_src }}"
      dest: "{{ ssh_priv_key_file }}"
      mode: "0600"

  - name: Ensure github.com is a known host
    lineinfile:
      dest: "{{ ssh_known_hosts_file }}"
      create: yes
      state: present
      line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
      regexp: "^github\\.com"
  become: yes
  become_user: "{{ ssh_user }}"
